export const ThemeTags = {
  // 1. Layout Tags - Describe the structural shape of the theme.
  singleCol: "single-column",
  twoCol: "two-column",
  threeCol: "three-column",
  sidebar: "sidebar",
  headerHeavy: "header-heavy",
  compact: "compact",
  wide: "wide",
  gridBased: "grid-based",
  timeline: "timeline",
  cardLayout: "card-layout",
  photoHeader: "photo-header",
  headshot: "headshot",
  noHeadshot: "no-headshot",
  sectioned: "sectioned",
  minimal: "minimal",
  heroFullscreen: "hero-fullscreen",

  // 2. Color & Tone Tags - Describe the palette and emotional feel.
  lightMode: "light-mode",
  darkMode: "dark-mode",
  highContrast: "high-contrast",
  lowContrast: "low-contrast",
  monoChrome: "monochrome",
  accented: "accented",
  warm: "warm",
  cool: "cool",
  neutral: "neutral",
  pastel: "pastel",
  bold: "bold",
  muted: "muted",
  editorial: "editorial",
  industrial: "industrial",
  playful: "playful",
  calm: "calm",
  energetic: "energetic",

  //3. Use‑Case Tags - Describe what the theme is best suited for.
  default: "default",
  resume: "resume",
  portfolio: "portfolio",
  developer: "developer",
  designer: "designer",
  product: "product",
  consultant: "consultant",
  academic: "academic",
  creative: "creative",
  corporate: "corporate",
  technical: "technical",
  executive: "executive",
  junior: "junior",
  senior: "senior",
  freelancer: "freelancer",
  caseStudy: "case-study",
  humorous: "humorous",
  retro: "retro",

  //4. Feature Tags - Describe functional or stylistic features.
  skillsFocused: "skills-focused",
  experienceHeavy: "experience-heavy",
  certifications: "certifications",
  icons: "icons",
  badges: "badges",
  photo: "photo",
  noPhoto: "no-photo",
  printFriendly: "print-friendly",
  compactSpacing: "compact-spacing",
  wideSpacing: "wide-spacing",
  typographyForward: "typography-forward",
  colorBlocks: "color-blocks",
  accentHeader: "accent-header",
  backgroundImage: "background-image",
  bordered: "bordered",
  rounded: "rounded",
  flat: "flat",

  //5. Miscellaneous
  funny: "funny",
  weird: "weird"
} as const;
export type ThemeTag = typeof ThemeTags[keyof typeof ThemeTags];
export default ThemeTags;
